spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mydata

logging:
  level:
    com.scm.dao.*: debug

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.lsh.scm.dao

server:
  port: 9000